In [1]:
import numpy as np

In [2]:
l = [3,4,5,6,7,"sudh"]

In [3]:
type(l)

list

In [4]:
type(np.array(l))

numpy.ndarray

In [5]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [6]:
np.array([[1,2,3,4]] , ndmin = 10)

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

In [7]:
np.mat([1,2,3])

matrix([[1, 2, 3]])

In [8]:
arr = np.array([3,4,5,6,7])

In [9]:
arr

array([3, 4, 5, 6, 7])

In [10]:
arr[0:3:2]

array([3, 5])

In [10]:
arr = np.array([[1,2] , [3,4]])

In [11]:
arr

array([[1, 2],
       [3, 4]])

In [12]:
arr[1][1]

4

In [13]:
#alternative
arr[1,1]

4

In [15]:
arr = np.array([[1,2] , [3,4] , [4,5]])

In [16]:
arr

array([[1, 2],
       [3, 4],
       [4, 5]])

In [17]:
arr[2][1]

5

In [18]:
arr[2,1]

5

In [8]:
np.asarray([3,4,5,6])

array([3, 4, 5, 6])

In [9]:
np.asarray([3,4,5,6],dtype = np.float64)

array([3., 4., 5., 6.])

In [10]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [11]:
np.asanyarray(np.mat([1,2,3,4])) #as matrix is subclass to array thats why asanyarray won't change the dtype from matrix to array

matrix([[1, 2, 3, 4]])

# np.fromfunction()

In [15]:
np.fromfunction(lambda i , j :i**j ,(3,3) ,dtype = int  ) #fromfunction will generate a array in terms of different conditions and shape

array([[1, 0, 0],
       [1, 1, 1],
       [1, 2, 4]])

In [16]:
np.fromfunction(lambda i , j :i+j ,(3,3) ,dtype = int  )

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [18]:
np.fromfunction(lambda i , j , k  :i+j + k ,(3,3 ,3) ,dtype = int  ) #here array is 3 dimensional as shape is (3,3,1) and that means 3 rows 1 column will genearate 3 times

array([[[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]],

       [[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]])

# iterable and iterator

In [38]:
for i in 5 :
    print(i)

TypeError: 'int' object is not iterable

In [39]:
for i in "sudh" :
    pass

In [40]:
for i in "s" :
    pass

In [42]:
for i in [2,3,4,5,5]:
    pass


In [43]:
s= "sudh"
next(s)

TypeError: 'str' object is not an iterator

In [44]:
 l = [1,2,3,4,5]

In [45]:
next(l)

TypeError: 'list' object is not an iterator

In [47]:
r = range(4)

In [48]:
next(r)

TypeError: 'range' object is not an iterator

In [33]:
s = "sudh"

In [36]:
i = iter(s) #iter() converts iterable items into iterator 

In [37]:
next(i) # next() works only for iterator items

's'

In [38]:
next(i)

'u'

In [39]:
next(i)

'd'

In [40]:
next(i)

'h'

In [41]:
next(i)

StopIteration: 

In [19]:
for i in "sudh" : #here 'sudh' is iterable, and for function convert this iterable string into iterator. That's why next() is working here in the background.
    print(i)

s
u
d
h


In [58]:
l

[1, 2, 3, 4, 5]

In [59]:
next(l)

TypeError: 'list' object is not an iterator

In [60]:
i  = iter(l)

In [61]:
next(i)

1

In [62]:
next(i)

2

In [63]:
next(i)

3

In [79]:
np.fromiter([1,2,3,4,5]) #Create a new 1-dimensional array from an iterable object.

TypeError: fromiter() missing required argument 'dtype' (pos 2)

In [80]:
np.fromiter([1,2,3,4,5] , dtype = float )

array([1., 2., 3., 4., 5.])

In [81]:
np.fromstring('3 2 4' , sep = " ")

array([3., 2., 4.])

In [20]:
pip install pandoc

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ------------------------------------ 127.0/127.0 kB 748.8 kB/s eta 0:00:00
     ---------------------------------------- 49.6/49.6 kB 2.5 MB/s eta 0:00:00
  Running setup.py install for pandoc: started
  Running setup.py install for pandoc: finished with status 'done'
Note: you may need to restart the kernel to use updated packages.


  DEPRECATION: pandoc is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [82]:
l = [[3,4,5,6],[7,8,9,5]]

In [83]:
arr  = np.array(l)

In [84]:
arr

array([[3, 4, 5, 6],
       [7, 8, 9, 5]])

In [85]:
arr.ndim

2

In [86]:
arr.size

8

In [87]:
arr.shape

(2, 4)

In [88]:
arr.dtype

dtype('int32')

In [89]:
list(range(0,7.6))

TypeError: 'float' object cannot be interpreted as an integer

In [90]:
np.arange(0,4.6,.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5])

# np.linspace() is widely used to generate a array for a given interval

In [100]:
np.linspace(1,5,num=100) #np.linspace(start, stop, num=50) here by default num=5o
#Return evenly spaced numbers over a specified interval

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [91]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [92]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [93]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [96]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [97]:
np.ones((4,5)) +1

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

# np.empty() is used to generate a array of given shape

In [114]:
np.empty((3,5), dtype=int) #Return a new array of given shape and type

array([[         0,          0,          0,          0,          0],
       [         0,          0,          0,          0,          0],
       [      1788,          0,          0, 1836404256,          0]])

In [103]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
np.random.rand(100000,5)

array([[0.86215309, 0.08646094, 0.07054641, 0.51647822, 0.77413419],
       [0.89605626, 0.69702493, 0.20700753, 0.01845333, 0.07281586],
       [0.91541735, 0.73145669, 0.97233119, 0.30211373, 0.96986468],
       ...,
       [0.76818744, 0.36794394, 0.66840709, 0.94292678, 0.24538308],
       [0.47549893, 0.97129735, 0.6599032 , 0.69779161, 0.83719437],
       [0.40234125, 0.28232897, 0.05782138, 0.86381235, 0.95627058]])

In [100]:
np.random.randn(4,5)

array([[ 0.10631835, -0.7357358 , -0.83788852, -1.46011273, -0.3031901 ],
       [-0.95213791,  0.4880427 ,  0.51661042, -1.70501338, -0.26025695],
       [ 1.09830715,  0.48273668, -0.11925987,  0.18701985, -1.89840409],
       [ 0.05776083,  0.73568015, -0.25949895,  0.41902531,  0.728015  ]])

In [104]:
np.random.randint(3,40,size=  60)

array([30, 39,  8, 20, 18, 26,  3, 25, 20,  6, 36,  3,  7, 34,  3, 33, 10,
       10, 15,  4,  3, 12, 35, 21, 28, 16, 19, 22, 21, 28, 14, 34, 18, 32,
        8,  9, 30,  4, 32,  3,  6, 17, 37, 21, 20, 27, 15, 39, 13, 33, 28,
       29, 27, 39,  7, 35, 21, 33, 18, 39])

In [106]:
arr = np.random.randint(2,7 , (4,5))

In [107]:
arr.shape

(4, 5)

In [108]:
arr


array([[6, 6, 3, 4, 5],
       [5, 5, 5, 4, 3],
       [4, 6, 4, 5, 5],
       [6, 4, 4, 2, 4]])

In [109]:
arr.reshape(1,4,5)

array([[[6, 6, 3, 4, 5],
        [5, 5, 5, 4, 3],
        [4, 6, 4, 5, 5],
        [6, 4, 4, 2, 4]]])

In [110]:
arr.reshape(10,2)

array([[6, 6],
       [3, 4],
       [5, 5],
       [5, 5],
       [4, 3],
       [4, 6],
       [4, 5],
       [5, 6],
       [4, 4],
       [2, 4]])

In [111]:
arr

array([[6, 6, 3, 4, 5],
       [5, 5, 5, 4, 3],
       [4, 6, 4, 5, 5],
       [6, 4, 4, 2, 4]])

In [113]:
arr.max()

6

In [114]:
arr

array([[6, 6, 3, 4, 5],
       [5, 5, 5, 4, 3],
       [4, 6, 4, 5, 5],
       [6, 4, 4, 2, 4]])

In [116]:
arr[0,1] = 3454

In [117]:
arr

array([[   6, 3454,    3,    4,    5],
       [   5,    5,    5,    4,    3],
       [   4,    6,    4,    5,    5],
       [   6,    4,    4,    2,    4]])

In [124]:
mat1 = np.random.randint( 1,4,(3,3))

In [130]:
mat1

array([[1, 2, 1],
       [2, 1, 3],
       [2, 2, 1]])

In [131]:
mat2

array([[2, 3, 3],
       [3, 1, 1],
       [3, 1, 2]])

In [132]:
mat1@mat2

array([[11,  6,  7],
       [16, 10, 13],
       [13,  9, 10]])

In [126]:
mat2 = np.random.randint( 1,4,(3,3))

In [127]:
mat2

array([[2, 3, 3],
       [3, 1, 1],
       [3, 1, 2]])

In [128]:
mat1*mat2

array([[2, 6, 3],
       [6, 1, 3],
       [6, 2, 2]])

In [133]:
arr

array([[   6, 3454,    3,    4,    5],
       [   5,    5,    5,    4,    3],
       [   4,    6,    4,    5,    5],
       [   6,    4,    4,    2,    4]])

In [135]:
arr/0

<ipython-input-135-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [134]:
1/0

ZeroDivisionError: division by zero

In [136]:
arr.T

array([[   6,    5,    4,    6],
       [3454,    5,    6,    4],
       [   3,    5,    4,    4],
       [   4,    4,    5,    2],
       [   5,    3,    5,    4]])

In [137]:
arr

array([[   6, 3454,    3,    4,    5],
       [   5,    5,    5,    4,    3],
       [   4,    6,    4,    5,    5],
       [   6,    4,    4,    2,    4]])

In [139]:
arr**2

array([[      36, 11930116,        9,       16,       25],
       [      25,       25,       25,       16,        9],
       [      16,       36,       16,       25,       25],
       [      36,       16,       16,        4,       16]], dtype=int32)

In [140]:
np.exp(arr)

<ipython-input-140-16c1c90aa297>:1: RuntimeWarning: overflow encountered in exp
  np.exp(arr)


array([[403.42879349,          inf,  20.08553692,  54.59815003,
        148.4131591 ],
       [148.4131591 , 148.4131591 , 148.4131591 ,  54.59815003,
         20.08553692],
       [ 54.59815003, 403.42879349,  54.59815003, 148.4131591 ,
        148.4131591 ],
       [403.42879349,  54.59815003,  54.59815003,   7.3890561 ,
         54.59815003]])

In [141]:
np.log10(arr)

array([[0.77815125, 3.53832233, 0.47712125, 0.60205999, 0.69897   ],
       [0.69897   , 0.69897   , 0.69897   , 0.60205999, 0.47712125],
       [0.60205999, 0.77815125, 0.60205999, 0.69897   , 0.69897   ],
       [0.77815125, 0.60205999, 0.60205999, 0.30103   , 0.60205999]])

In [143]:
np.sqrt(arr)

array([[ 2.44948974, 58.77074102,  1.73205081,  2.        ,  2.23606798],
       [ 2.23606798,  2.23606798,  2.23606798,  2.        ,  1.73205081],
       [ 2.        ,  2.44948974,  2.        ,  2.23606798,  2.23606798],
       [ 2.44948974,  2.        ,  2.        ,  1.41421356,  2.        ]])

In [144]:
np.pi

3.141592653589793